package com.android.stickerpocket.utils

object AppConstants {
    const val SEND_STICKER_FROM_APP = "SEND_STICKER_FROM_APP"
    const val SEND_STICKER_FROM_KEYBOARD = "SEND_STICKER_FROM_KEYBOARD"
    const val OPEN_STICKER_POCKET_KEYBOARD = "OPEN_STICKER_POCKET_KEYBOARD"
    const val SETUP_STICKER_POCKET_KEYBOARD = "SETUP_STICKER_POCKET_KEYBOARD"
    const val DOWNLOAD_STICKER = "DOWNLOAD_STICKER"
    const val MANAGE_STICKERS = "MANAGE_STICKERS"
    const val ADD_TAG_TO_STICKER = "ADD_TAG_TO_STICKER"
    const val REORDER_STICKERS = "REORDER_STICKERS"
    const val MOVE_STICKER_TO_NEW_POCKET = "MOVE_STICKER_TO_NEW_POCKET"
    const val MOVE_MULTIPLE_STICKER_TO_NEW_POCKET = "MOVE_MULTIPLE_STICKER_TO_NEW_POCKET"
    const val MANAGE_POCKETS = "MANAGE_POCKETS"
    const val REORGANIZE_POCKET = "REORGANIZE_POCKET"
    const val WELCOME_MESSAGE = "WELCOME_MESSAGE"
    const val STICKER_POCKET_LAYOUT = "STICKER_POCKET_LAYOUT"
    const val IMPORT_STICKER_FROM_WHATSAPP = "IMPORT_STICKER_FROM_WHATSAPP"
    const val IMPORT_STICKER_FROM_PHOTO = "IMPORT_STICKER_FROM_PHOTO"
}